PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dummy: <http://rdf.biosemantics.org/ontologies/dummy/>
PREFIX rdcMeta: <http://rdf.biosemantics.org/ontologies/rd-connect/>
PREFIX iao: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?phenotypeURI ?phenotype   {      
    
  {
    ?phenotypeURI  rdfs:subClassOf* <#phenotype#>.    
    ?phenotypeURI rdfs:label ?phenotype.
  }
} 