PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dummy: <http://rdf.biosemantics.org/ontologies/dummy/>
PREFIX rdcMeta: <http://rdf.biosemantics.org/ontologies/rd-connect/>
PREFIX iao: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?collection ?collectionURI  ?datasetURI ?dataset ?fdpURI ?fdp {   
  VALUES(?type) {(<#collection#>)} 
  VALUES ?fdpURI {#fdp#} 
  
  {
    ?collectionURI skos:exactMatch ?uri1.
  }
  UNION
  {
    ?uri2 skos:exactMatch ?collectionURI.
  }
  
  
    
      
    GRAPH ?distributionURI{
     ?collectionURI a ?type;
                      dct:title ?collection.
                      
     }
     
    GRAPH ?fdpURI {
      ?datasetURI dct:title ?dataset;
                      dcat:distribution ?distributionURI.   
    }
          
    ?fdpURI dct:title ?fdp.  
  
} GROUP BY ?collection ?collectionURI  ?datasetURI ?dataset ?fdpURI ?fdp