PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dummy: <http://rdf.biosemantics.org/ontologies/dummy/>
PREFIX rdcMeta: <http://rdf.biosemantics.org/ontologies/rd-connect/>
PREFIX iao: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?collection1URI ?collection1 ?collection2URI ?collection2 {   
  VALUES(?type) {(<#collection#>)} 
  VALUES ?fdpURI {#fdp#} 
  
   ?collection1URI skos:exactMatch ?collection2URI.
  
     ?collection1URI a ?type;
                      dct:title ?collection1. 
  
  ?collection2URI a ?type;
                      dct:title ?collection2. 
    
  
} 