PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dummy: <http://rdf.biosemantics.org/ontologies/dummy/>
PREFIX rdcMeta: <http://rdf.biosemantics.org/ontologies/rd-connect/>
PREFIX iao: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?collectionURI ?collection ?datasetURI ?dataset ?fdpURI ?fdp {      
   VALUES(?textInput) {("#plainText#")}  
   VALUES ?fdpURI {#fdp#}  
    
    
      
    GRAPH ?distributionURI{
     ?collectionURI a <http://semanticscience.org/resource/SIO_000616>;
                      dct:title ?collection.
                      
     }
     
     FILTER regex(str(?collection), ?textInput, "i") .
     
    GRAPH ?fdpURI {
      ?datasetURI dct:title ?dataset;
                      dcat:distribution ?distributionURI.   
    }
          
    ?fdpURI dct:title ?fdp.    
  
}